name: Coverage of the tests

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Configuration JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Giving execute permission to mvnw
        run: chmod +x mvnw
        
      - name: Generate coverage report
        run: |
          ./mvnw jacoco:report        
        
      - name: Build and execute tests
        run: |
          ./mvnw clean install -B
          ./mvnw test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Link to coverage report
        run: |
          echo "Here is the link to the coverage report"
          echo "[Link coverage](https://app.codecov.io/gh/ANGELVBR/app-management)"      
 
