name: Java Maven Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
          
      - name: Giving execute permission to mvnw
        run: chmod +x ./ms-database/mvnw          
          
      - name: Build with Maven Ms-database
        run: ./ms-database/mvnw clean compile

      - name: Run tests
        run: ./ms-database/mvnw test
